-- Usuarios, equipes e o vinculo entre os dois.
--
-- E o alicerce da regra de visibilidade (CLAUDE.md#visibilidade): quem enxerga um ticket
-- depende do papel global do usuario e das equipes de que ele participa.
--
-- UM USUARIO PERTENCE A VARIAS EQUIPES. O UNIQUE de team_memberships e sobre o par
-- (user_id, team_id), nunca sobre user_id sozinho. E por isso que existe uma tabela de
-- vinculo em vez de uma coluna em users, e e por isso que a visibilidade fala em "as
-- equipes do usuario" no plural, mesmo quando ha so uma.
--
-- ENUMS SAO VARCHAR + CHECK, nao o tipo ENUM do Postgres. O @Enumerated(STRING) do JPA
-- le VARCHAR direto, o `ddl-auto: validate` confere a coluna, e acrescentar um valor
-- novo e uma migration trivial em vez de um ALTER TYPE que nao roda dentro de
-- transacao em versoes antigas do Postgres.
--
-- AS LARGURAS ABAIXO SAO CONTRATO. As entidades das Fases 2 e 3 devem repeti-las em
-- @Column(length = ...). Nao conte com o `ddl-auto: validate` para pegar uma divergencia
-- de tamanho: contra Postgres ele compara o tipo, e o metadado do driver traz "varchar"
-- sem o limite. Quem cobra e o banco, no INSERT, com "value too long for type" — em
-- producao, e nao no boot.
--
-- Sem DEFAULT em created_at/updated_at de proposito: quem preenche esses campos e a
-- auditoria do Spring Data (config/JpaConfig). Um DEFAULT no banco esconderia uma
-- auditoria desligada em vez de deixar o INSERT falhar.

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    -- Guardada sempre em minusculas, garantido pelo CHECK abaixo. Isso deixa o UNIQUE
    -- comum resolver a unicidade sem distinguir caixa e, o que importa mais, deixa o
    -- `WHERE email = ?` da busca por login usar o indice — um indice sobre lower(email)
    -- pareceria equivalente e seria ignorado por essa consulta.
    email         VARCHAR(320)             NOT NULL,
    full_name     VARCHAR(150)             NOT NULL,
    -- O BCrypt ocupa 60; os 100 sao folga para uma troca futura de algoritmo, que mexeria
    -- no CHECK logo abaixo mas nao na largura da coluna.
    password_hash VARCHAR(100)             NOT NULL,
    role          VARCHAR(20)              NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT users_pk PRIMARY KEY (id),
    CONSTRAINT users_email_unique UNIQUE (email),
    -- 'Ana@empresa.com' e 'ana@empresa.com' sao a mesma pessoa. Sem esta regra, o sistema
    -- aceitaria duas contas para ela — duas contas com visibilidades diferentes sobre os
    -- mesmos tickets — e quem se cadastrasse com maiuscula nao conseguiria entrar
    -- digitando minusculas. Normalizar no banco vale mais do que confiar em todo INSERT
    -- futuro lembrar de chamar lower().
    CONSTRAINT users_email_is_lowercase CHECK (email = lower(email)),
    CONSTRAINT users_role_check CHECK (role IN ('REQUESTER', 'AGENT', 'ADMIN')),
    -- Exige um BCrypt COMPLETO: prefixo, custo de dois digitos e exatamente 53 caracteres
    -- de sal + digest no alfabeto do BCrypt. Total fixo de 60.
    --
    -- A regra existe porque a alternativa falha em silencio: com a variavel de ambiente
    -- nao definida, o seed gravou aqui o texto literal '${ADMIN_PASSWORD_HASH}', a
    -- aplicacao subiu normalmente e so o primeiro login revelaria o problema.
    --
    -- Conferir so o prefixo nao bastaria, e por um motivo concreto: um hash truncado no
    -- meio do caminho — variavel cortada por ferramenta de deploy, copy-paste incompleto —
    -- tem o prefixo certo, passaria, e o admin ficaria sem conseguir entrar para sempre,
    -- de novo sem ninguem avisar. E o mesmo modo de falha, com outra roupa.
    --
    -- Trocar de algoritmo exige uma migration que afrouxe este CHECK. Deliberado: e uma
    -- decisao que merece aparecer num diff, nao passar despercebida.
    CONSTRAINT users_password_hash_is_bcrypt
        CHECK (password_hash ~ '^\$2[aby]\$[0-9]{2}\$[./A-Za-z0-9]{53}$')
);

CREATE TABLE teams
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(100)             NOT NULL,
    description VARCHAR(500),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT teams_pk PRIMARY KEY (id)
);

-- Aqui, ao contrario de users.email, o indice e sobre a expressao: o nome da equipe e
-- texto de exibicao e precisa guardar a caixa que a pessoa escreveu ("Suporte N1"). Como
-- nao ha busca por nome exato no caminho de login, o indice funcional basta.
-- "Suporte" e "suporte" continuam sendo uma equipe so.
CREATE UNIQUE INDEX teams_name_unique_idx ON teams (lower(name));

CREATE TABLE team_memberships
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT                   NOT NULL,
    team_id    BIGINT                   NOT NULL,
    role       VARCHAR(20)              NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT team_memberships_pk PRIMARY KEY (id),
    -- CASCADE porque o vinculo nao significa nada sem as duas pontas: mantido como
    -- linha orfa, ele viraria uma equipe fantasma dentro da query de visibilidade.
    CONSTRAINT team_memberships_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT team_memberships_team_fk FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE CASCADE,
    CONSTRAINT team_memberships_role_check CHECK (role IN ('MEMBER', 'LEAD')),
    -- O par e unico; o usuario, nao. Trocar de MEMBER para LEAD e um UPDATE, nao uma
    -- linha nova.
    CONSTRAINT team_memberships_user_team_unique UNIQUE (user_id, team_id)
);

-- A visibilidade consulta nos dois sentidos: "de que equipes este usuario participa" e
-- "quem esta nesta equipe". O UNIQUE acima ja sustenta o primeiro, porque user_id e a
-- coluna a esquerda; este indice sustenta o segundo.
CREATE INDEX team_memberships_team_idx ON team_memberships (team_id);
