-- Tickets, comentarios e o roteamento de categoria para equipe.
--
-- OS DOIS MODOS DE ATRIBUICAO SAO REGRA DO BANCO (CLAUDE.md#atribuicao). Um ticket esta
-- sempre em exatamente um deles:
--
--   modo equipe     -> assigned_team_id preenchido; current_assignee_id opcional
--   modo exclusivo  -> exclusive_assignee_id preenchido; origin_team_id obrigatorio
--
-- A entidade Ticket tambem garante isso, mas UPDATE escrito a mao, script de correcao ou
-- um adaptador futuro passam por fora dela. Os CHECKs abaixo sao o que continua valendo
-- nesses casos, e TicketsSchemaIT prova cada um.
--
-- ENUMS SAO VARCHAR + CHECK, pelo mesmo motivo registrado na V2: o @Enumerated(STRING)
-- le direto, e valor novo e uma migration trivial em vez de ALTER TYPE.
--
-- AS LARGURAS SAO CONTRATO, repetidas nas entidades e nos DTOs. O `ddl-auto: validate`
-- nao confere tamanho contra Postgres.
--
-- A AUDITORIA NAO ESTA AQUI. O roadmap previa comentarios e auditoria juntos numa V6;
-- os comentarios entraram com o nucleo de tickets, e a auditoria fica para a migration
-- da Fase 6, com o primeiro listener.

CREATE TABLE tickets
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title                 VARCHAR(200)             NOT NULL,
    description           VARCHAR(10000)           NOT NULL,
    status                VARCHAR(20)              NOT NULL,
    priority              VARCHAR(10)              NOT NULL,
    category              VARCHAR(20)              NOT NULL,
    requester_id          BIGINT                   NOT NULL,
    assigned_team_id      BIGINT,
    current_assignee_id   BIGINT,
    exclusive_assignee_id BIGINT,
    origin_team_id        BIGINT,
    -- Controle otimista de concorrencia. Duas transicoes simultaneas a partir do mesmo
    -- status passariam as duas pela validacao e a segunda sobrescreveria a primeira, com
    -- dois eventos publicados para um historico que so aconteceu pela metade.
    version               BIGINT                   NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT tickets_pk PRIMARY KEY (id),
    -- RESTRICT, e nao CASCADE, em todas as referencias: ticket e historico. Apagar uma
    -- pessoa ou uma equipe nao pode levar chamados — e os comentarios deles — junto.
    CONSTRAINT tickets_requester_fk FOREIGN KEY (requester_id) REFERENCES users (id),
    CONSTRAINT tickets_assigned_team_fk FOREIGN KEY (assigned_team_id) REFERENCES teams (id),
    CONSTRAINT tickets_current_assignee_fk FOREIGN KEY (current_assignee_id) REFERENCES users (id),
    CONSTRAINT tickets_exclusive_assignee_fk FOREIGN KEY (exclusive_assignee_id) REFERENCES users (id),
    CONSTRAINT tickets_origin_team_fk FOREIGN KEY (origin_team_id) REFERENCES teams (id),
    CONSTRAINT tickets_status_check
        CHECK (status IN ('OPEN', 'IN_PROGRESS', 'WAITING_CUSTOMER', 'RESOLVED', 'CLOSED', 'REOPENED')),
    CONSTRAINT tickets_priority_check CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
    CONSTRAINT tickets_category_check CHECK (category IN ('HARDWARE', 'SOFTWARE', 'ACCESS', 'OTHER')),
    CONSTRAINT tickets_title_not_blank CHECK (btrim(title) <> ''),
    CONSTRAINT tickets_description_not_blank CHECK (btrim(description) <> ''),
    -- Exatamente um modo: a equipe OU o responsavel exclusivo, nunca os dois, nunca nenhum.
    -- Sem modo nenhum, o ticket nao seria visto por membro nenhum e ninguem o atenderia.
    CONSTRAINT tickets_exactly_one_assignment_mode
        CHECK ((assigned_team_id IS NULL) <> (exclusive_assignee_id IS NULL)),
    -- A origem existe se, e somente se, o ticket esta em modo exclusivo. Sem ela o lider
    -- perderia de vista o ticket que saiu da equipe; sobrando em modo equipe, daria a outro
    -- lider uma visibilidade que ninguem concedeu.
    CONSTRAINT tickets_origin_team_only_in_exclusive_mode
        CHECK ((exclusive_assignee_id IS NULL) = (origin_team_id IS NULL)),
    -- Responsavel atual e conceito do modo equipe: qualquer membro pode assumir o lugar
    -- dele. Em modo exclusivo quem atua e o responsavel exclusivo, e mais ninguem.
    CONSTRAINT tickets_current_assignee_only_in_team_mode
        CHECK (current_assignee_id IS NULL OR assigned_team_id IS NOT NULL)
);

-- Uma coluna por pergunta da regra de visibilidade (CLAUDE.md#visibilidade): "os meus",
-- "os da equipe", "os atribuidos a mim" e "os que sairam da equipe que lidero". A Fase 5
-- filtra por elas na query, e cada uma precisa de indice para o filtro nao virar varredura.
CREATE INDEX tickets_requester_idx ON tickets (requester_id);
CREATE INDEX tickets_assigned_team_idx ON tickets (assigned_team_id);
CREATE INDEX tickets_exclusive_assignee_idx ON tickets (exclusive_assignee_id);
CREATE INDEX tickets_origin_team_idx ON tickets (origin_team_id);

CREATE TABLE ticket_comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ticket_id  BIGINT                   NOT NULL,
    author_id  BIGINT                   NOT NULL,
    body       VARCHAR(5000)            NOT NULL,
    -- NOT NULL e sem DEFAULT: a flag decide se o solicitante le o comentario. Um default
    -- tomaria essa decisao por quem esqueceu de toma-la.
    internal   BOOLEAN                  NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ticket_comments_pk PRIMARY KEY (id),
    -- CASCADE aqui, ao contrario de tickets: comentario nao tem sentido sem o ticket.
    CONSTRAINT ticket_comments_ticket_fk FOREIGN KEY (ticket_id) REFERENCES tickets (id) ON DELETE CASCADE,
    CONSTRAINT ticket_comments_author_fk FOREIGN KEY (author_id) REFERENCES users (id),
    CONSTRAINT ticket_comments_body_not_blank CHECK (btrim(body) <> '')
);

-- A conversa de um ticket e lida sempre inteira e em ordem.
CREATE INDEX ticket_comments_ticket_idx ON ticket_comments (ticket_id, id);

-- Qual equipe recebe os tickets de cada categoria. O solicitante escolhe a categoria e
-- nunca precisa conhecer as equipes.
--
-- Categoria sem rota recusa a abertura, em vez de cair numa equipe default: um default
-- esconderia a configuracao que falta, e os tickets iriam parar onde ninguem espera.
CREATE TABLE ticket_routes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    category   VARCHAR(20)              NOT NULL,
    team_id    BIGINT                   NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ticket_routes_pk PRIMARY KEY (id),
    CONSTRAINT ticket_routes_category_unique UNIQUE (category),
    CONSTRAINT ticket_routes_category_check CHECK (category IN ('HARDWARE', 'SOFTWARE', 'ACCESS', 'OTHER')),
    -- RESTRICT: apagada em cascata, a rota sumiria e a proxima abertura daquela categoria
    -- falharia sem ninguem ter mexido no roteamento.
    CONSTRAINT ticket_routes_team_fk FOREIGN KEY (team_id) REFERENCES teams (id)
);
