@startuml
title <size:24>Autenticacao</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System_Boundary("TicketSystemApplication_boundary", "TicketSystemApplication", $tags="") {
  Container_Boundary("TicketSystemApplication.TicketSystemApplication_boundary", "TicketSystemApplication", $tags="") {
    Component(TicketSystemApplication.TicketSystemApplication.Comum, "Comum", $techn="Module", $descr="", $tags="", $link="")
    Component(TicketSystemApplication.TicketSystemApplication.Usuarios, "Usuarios", $techn="Module", $descr="", $tags="", $link="")
    Component(TicketSystemApplication.TicketSystemApplication.Autenticacao, "Autenticacao", $techn="Module", $descr="", $tags="", $link="")
  }

}

Rel(TicketSystemApplication.TicketSystemApplication.Autenticacao, TicketSystemApplication.TicketSystemApplication.Comum, "depends on", $techn="", $tags="", $link="")
Rel(TicketSystemApplication.TicketSystemApplication.Autenticacao, TicketSystemApplication.TicketSystemApplication.Usuarios, "uses", $techn="", $tags="", $link="")
Rel(TicketSystemApplication.TicketSystemApplication.Usuarios, TicketSystemApplication.TicketSystemApplication.Comum, "depends on", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml